- name: Create a new folder in Box
  hosts: localhost
  gather_facts: false

  tasks:

  - name: Create new Box folder
    create_box_folder:
      token: "wBmZCE9cPDa4uL9SImrFqRfembWhini9"
      file_name: "Test-automation.txt"
      file_path: ./
      parent_folder_id: 0
    register: box_files

  - name: Debug the output
    debug:
      var: box_files