- name: List all files in box
  hosts: localhost
  gather_facts: false


  tasks:


  - name: List all files and folders on box
    list_box_files:
      token: "Apikey123"
    register: box_files

  - name: Debug the output
    debug:
      var: box_files
