- name: List folder by folder id
  hosts: localhost
  gather_facts: false


  tasks:


  - name: List folder by folder id
    ansible_list_box_folder_id:
      token: "gSDmiysg4U89ftN6IPD9c8mZ4vHXPPDF"
      folder_id: 0
      fields: "created_by"
    register: box_files

  - name: Debug the output
    debug:
      var: box_files
